name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  my-job:
      runs-on: ubuntu-latest

      steps:
        - name: Free disk pace
          uses: jlumbroso/free-disk-space@v1.3.1
          with:
            tool-cache: false
            docker-images: false

        - name: Delete huge unnecessary tools folder
          run: rm -rf /opt/hostedtoolcache

        - name: Free space
          run: |
            echo "Free space:"
            df -h

        - name: Check out code
          uses: actions/checkout@v4

        - name: Setup Cog
            uses: replicate/setup-cog@v2
            with:
              token: ${{ secrets.REPLICATE_API_TOKEN }}

        - name: Push to Replicate
          run: |
            cog push r8.im/mrlensun/any-comfyui-workflow
